[theme]
base                = "light"
primaryColor        = "#c15b1c"  # Butonlar ve vurgular icin sıcak turuncu/amber tonu
backgroundColor     = "#ecce64f5"  # Arka plan icin cok acik, gozu yormayan krem/fildisi tonu
secondaryBackgroundColor = "#953d27" # Yan menu ve kutular icin hafif kahve/krem tonu
textColor           = "#000000"  # Tum yazilarin net okunmasi icin tamamen Siyah
font                = "sans serif"

[server]
headless            = true
runOnSave           = false

[browser]
gatherUsageStats    = false
